"""Core types for the backtest system.

These types define the interface contracts between Engine, Strategy, and Executor.
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Optional

from src.backtest.executor.base import OptionContract, Position


class Side(Enum):
    BUY = "BUY"
    SELL = "SELL"


@dataclass
class Order:
    """A trading order generated by Strategy and executed by Executor."""

    symbol: str
    side: Side
    quantity: int
    reason: str = ""
    instrument_type: str = "option"       # "option" | "stock"
    option_type: Optional[str] = None     # "put" | "call" (for options)
    strike_selection: str = "atm"         # "atm" | "otm_1" | specific float as str
    reference_price: float = 0.0          # underlying price for strike selection (e.g. stock close)


@dataclass
class OrderResult:
    """Result of executing an Order through the Executor."""

    order: Order
    status: str                           # "FILLED" | "REJECTED"
    fill_price: float = 0.0
    fill_time: Optional[datetime] = None
    contract: Optional[OptionContract] = None
    reject_reason: str = ""


@dataclass
class PortfolioState:
    """Snapshot of the portfolio at a given point in time."""

    cash: float
    positions: list[Position] = field(default_factory=list)
    equity: float = 0.0

    def get_position(self, symbol: str) -> Optional[Position]:
        """Get position for a specific underlying symbol, or None."""
        return next((p for p in self.positions if p.contract.symbol == symbol), None)


@dataclass
class Quote:
    """Price quote at a specific point in time."""

    open: float
    high: float
    low: float
    close: float
    volume: int
    timestamp: Optional[datetime] = None
